version: "3"
services:
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan/work

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: electionmoney
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d/:ro
